spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/external
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: a12345678

  jpa:
    hibernate:
      ddl-auto: create-drop

  application:
    name: STATUS-PROD

custom:
  value: PROD